logging:
  level:
    root: INFO
    ca.purpleowl.examples: TRACE

server:
  port: 8085

spring:
  datasource:
    data-username: SA
    data-password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:example
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: h2
